# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:38
from __future__ import unicode_literals

import Lagerregal.utils
from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Manual = apps.get_model("devices", "Manual")
    Device = apps.get_model("devices", "Device")
    db_alias = schema_editor.connection.alias
    for device in Device.objects.using(db_alias).all():
        if device.manual:
            Manual.objects.using(db_alias).create(name="manual", device=device, location=device.manual)

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_python3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(blank=True, null=True, upload_to=Lagerregal.utils.get_file_location)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='manual',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.RunPython(forwards_func),        
        migrations.RemoveField(
            model_name='device',
            name='manual',
        ),

    ]
