# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='column',
            field=models.CharField(choices=[('l', 'left'), ('r', 'right')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widgetname',
            field=models.CharField(choices=[('bookmarks', 'Bookmarked Devices'), ('recentlendings', 'Recent lendings'), ('overdue', 'Overdue devices'), ('groups', 'Groups'), ('newestdevices', 'Newest devices'), ('edithistory', 'Edit history'), ('statistics', 'Statistics'), ('sections', 'Sections'), ('shorttermdevices', 'Devices for short term lending'), ('returnsoon', 'Devices, that are due soon')], max_length=200),
        ),
    ]
