# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_python3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widgetname',
            field=models.CharField(choices=[('returnsoon', 'Devices, that are due soon'), ('groups', 'Groups'), ('overdue', 'Overdue devices'), ('recentlendings', 'Recent lendings'), ('bookmarks', 'Bookmarked Devices'), ('edithistory', 'Edit history'), ('newestdevices', 'Newest devices'), ('sections', 'Sections'), ('statistics', 'Statistics'), ('shorttermdevices', 'Devices for short term lending')], max_length=200),
        ),
    ]
