# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20171026_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='usage',
            field=models.CharField(blank=True, choices=[('owner', 'person currently lending is changed'), ('overdue', 'Reminder that device is overdue'), ('new', 'New Device is created'), ('trashed', 'Device is trashed'), ('room', 'Room is changed'), ('reminder', 'Reminder that device is still owned')], max_length=200, null=True, verbose_name='Usage'),
        ),
    ]
