# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_python3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='usage',
            field=models.CharField(blank=True, choices=[('room', 'Room is changed'), ('overdue', 'Reminder that device is overdue'), ('reminder', 'Reminder that device is still owned'), ('owner', 'person currently lending is changed'), ('trashed', 'Device is trashed'), ('new', 'New Device is created')], max_length=200, null=True, verbose_name='Usage'),
        ),
    ]
